### Obtener todas las tareas
GET  http://localhost:4000/todos

### Obtener tarea unica
GET  http://localhost:4000/todos/d651081a-77e9-4e9b-a9ee-e11807875da0

### Agregar nueva tarea
POST  http://localhost:4000/todos
Content-Type: application/json

{
    "user_email": "pato3@gmail.com",
    "title": "crea Api",
    "progress": 5
}
### actualizar todos los parametros de una tarea
PUT  http://localhost:4000/todos/619e3be3-744b-447a-bbfd-586b00c5ad59
Content-Type: application/json

{
    "user_email": "pato4@gmail.com",
    "title": "Probando put",
    "progress": 9
}
### actualizar datos parciales de una tarea
PATCH  http://localhost:4000/todos/619e3be3-744b-447a-bbfd-586b00c5ad59
Content-Type: application/json

{
    "title": "Probando patch"
}
### Elimina una tarea
DELETE  http://localhost:4000/todos/d651081a-77e9-4e9b-a9ee-e11807875da0